"""The core: data types, the component graph, and the compiler.

`batch`, `schema`, `ports`, `distributions` and `rows` are the vocabulary
everything else is stated against (P1). `graph`, `recipe` and `compile` are
what turns a declarative assembly of components and objectives into a checked,
printable execution plan (P2, `DESIGN.md` §2.1, §3, §7, §8, §9.1). `loss`,
`schedules` and `optimisation` are the objective, weighting and descent
contracts the compiler reads (P3, P4, §4, §6, §7) — they are in the leaf layer
because `training/` imports `core/` and never the reverse, which is the same
reason `DESIGN.md` §10 gives for `Stage`.
"""

from xty2.core.batch import XTYBatch, assert_unchanged_by
from xty2.core.card_keys import (
    CARD_KEY_SECTIONS,
    CARD_KEY_VOCABULARY,
    REQUIRED,
    card_hyperparameters,
    is_required,
    validate_card_key,
)
from xty2.core.compile import (
    CompiledObjective,
    CompiledRun,
    CompiledStage,
    ExecutionPlan,
    ForwardPass,
    PlannedComponent,
    compile,
    plan_digest_of,
)
from xty2.core.conformance import (
    check_outcome_distribution_contract,
    check_treatment_distribution_contract,
)
from xty2.core.distributions import (
    CategoricalTreatment,
    GaussianOutcome,
    OutcomeDistribution,
    TreatmentDistribution,
    TreatmentMode,
    treatment_mode,
)
from xty2.core.errors import (
    ArtifactError,
    BatchContractError,
    CardKeyError,
    CompileError,
    ContractError,
    GraphError,
    LossError,
    PortContractError,
    SchemaError,
    TrainingError,
    Xty2Error,
)
from xty2.core.graph import (
    DEFAULT,
    IDENTITY_VIEW,
    SOURCE_NAME,
    SOURCE_PORTS,
    Component,
    ComponentGraph,
    Params,
    PortView,
    Realisation,
    State,
    render_ports,
    source_ports,
)
from xty2.core.loss import (
    REDUCTIONS,
    LossTerm,
    Reduction,
    TrainContext,
    apply_reduction,
    candidate_treatments,
    outcome_distribution,
    reduce_rows,
    treatment_at,
    treatment_distribution,
    validate_reduction,
)
from xty2.core.optimisation import (
    OPTIMISER_NAMES,
    ClipMode,
    GradientClipping,
    OptimiserName,
    OptimiserSpec,
    WeightDecay,
    gradient_norm,
)
from xty2.core.ports import (
    PORT_SPECS,
    Axis,
    Port,
    PortSpec,
    PortValue,
    port_spec,
    resolve_shape,
)
from xty2.core.recipe import (
    Objective,
    Purpose,
    Recipe,
    Stage,
    Weighted,
    validate_rows,
)
from xty2.core.rows import (
    ROW_POPULATIONS,
    RowIndex,
    Rows,
    populations_are_disjoint,
    resolve_rows,
    row_mask,
    validate_population,
)
from xty2.core.schedules import (
    Constant,
    ExponentialDecay,
    Ramp,
    Schedule,
    Step,
    as_schedule,
)
from xty2.core.schema import FeatureSpec, OutcomeSpec, Schema

__all__ = [
    "CARD_KEY_SECTIONS",
    "CARD_KEY_VOCABULARY",
    "DEFAULT",
    "IDENTITY_VIEW",
    "OPTIMISER_NAMES",
    "PORT_SPECS",
    "REDUCTIONS",
    "REQUIRED",
    "ROW_POPULATIONS",
    "SOURCE_NAME",
    "SOURCE_PORTS",
    "ArtifactError",
    "Axis",
    "BatchContractError",
    "CardKeyError",
    "CategoricalTreatment",
    "ClipMode",
    "CompileError",
    "CompiledObjective",
    "CompiledRun",
    "CompiledStage",
    "Component",
    "ComponentGraph",
    "Constant",
    "ContractError",
    "ExecutionPlan",
    "ExponentialDecay",
    "FeatureSpec",
    "ForwardPass",
    "GaussianOutcome",
    "GradientClipping",
    "GraphError",
    "LossError",
    "LossTerm",
    "Objective",
    "OptimiserName",
    "OptimiserSpec",
    "OutcomeDistribution",
    "OutcomeSpec",
    "Params",
    "PlannedComponent",
    "Port",
    "PortContractError",
    "PortSpec",
    "PortValue",
    "PortView",
    "Purpose",
    "Ramp",
    "Realisation",
    "Recipe",
    "Reduction",
    "RowIndex",
    "Rows",
    "Schedule",
    "Schema",
    "SchemaError",
    "Stage",
    "State",
    "Step",
    "TrainContext",
    "TrainingError",
    "TreatmentDistribution",
    "TreatmentMode",
    "WeightDecay",
    "Weighted",
    "XTYBatch",
    "Xty2Error",
    "apply_reduction",
    "as_schedule",
    "assert_unchanged_by",
    "candidate_treatments",
    "card_hyperparameters",
    "check_outcome_distribution_contract",
    "check_treatment_distribution_contract",
    "compile",
    "gradient_norm",
    "is_required",
    "outcome_distribution",
    "plan_digest_of",
    "populations_are_disjoint",
    "port_spec",
    "reduce_rows",
    "render_ports",
    "resolve_rows",
    "resolve_shape",
    "row_mask",
    "source_ports",
    "treatment_at",
    "treatment_distribution",
    "treatment_mode",
    "validate_card_key",
    "validate_population",
    "validate_reduction",
    "validate_rows",
]
